'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const ROOT = path.join(__dirname, '..', '..');

/**
 * POST /api/initialise
 * Body: wizard config JSON
 * Streams SSE progress to the client.
 */
module.exports = async function initialise(req, res) {
    const cfg = req.body;

    // Set up SSE
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.flushHeaders();

    const step = (msg, ok = true) => {
        res.write(`data: ${JSON.stringify({ ok, msg })}\n\n`);
    };
    const done = (url) => {
        res.write(`data: ${JSON.stringify({ done: true, redirectUrl: url })}\n\n`);
        res.end();
    };
    const fail = (msg) => {
        res.write(`data: ${JSON.stringify({ ok: false, fatal: true, msg })}\n\n`);
        res.end();
    };

    try {
        // ── 1. Generate secrets ──────────────────────────────────────────────────
        step('Generating RS256 keypair…');
        const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
            modulusLength: 2048,
            publicKeyEncoding: { type: 'spki', format: 'pem' },
            privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
        });
        const adminToken = crypto.randomBytes(32).toString('hex');
        const nextAuthSecret = crypto.randomBytes(32).toString('hex');
        const aesKey = crypto.randomBytes(32).toString('hex');
        const revalidateSecret = crypto.randomBytes(32).toString('hex');
        step('Secrets generated ✓');

        // ── 2. Generate admin slug ───────────────────────────────────────────────
        const adminSlug = crypto.randomBytes(4).toString('hex') + '-admin';
        step(`Admin slug: /${adminSlug}`);

        // ── 3. Write project.config.ts ───────────────────────────────────────────
        step('Writing project.config.ts…');
        const configPath = path.join(ROOT, 'main-app', 'config', 'project.config.ts');

        const roles = cfg.roles.map(r =>
            `    { name: "${r.name}", color: "${r.color}", isDefault: ${r.isDefault} },`
        ).join('\n');

        const standardFields = Object.entries(cfg.standardFields).map(([k, v]) =>
            `      ${k}: { enabled: ${v.enabled}, required: ${v.required} },`
        ).join('\n');

        const customFields = JSON.stringify(cfg.customFields || [], null, 6)
            .replace(/^/gm, '');

        const configContent = `/**
 * project.config.ts — Generated by setup wizard
 * ⚠️  Do NOT edit manually. Re-run the wizard to change settings.
 * ⚠️  This file is excluded from git.
 */

export const projectConfig = {
  meta: {
    name: ${JSON.stringify(cfg.projectName)},
    description: ${JSON.stringify(cfg.tagline || '')},
    baseUrl: ${JSON.stringify(cfg.baseUrl)},
    supportEmail: ${JSON.stringify(cfg.supportEmail)},
    timezone: ${JSON.stringify(cfg.timezone)},
    setupComplete: true,
    adminSlug: ${JSON.stringify(adminSlug)},
  },
  auth: {
    providers: ${JSON.stringify(cfg.providers)},
    loginIdentifier: ${JSON.stringify(cfg.loginIdentifier)},
    requireEmailVerification: ${cfg.requireEmailVerification},
    rememberMe: { enabled: ${cfg.rememberMe.enabled}, days: ${cfg.rememberMe.days} },
    jwt: { expiryDefault: "1h", refreshExpiry: "30d" },
    passwordRules: {
      minLength: ${cfg.passwordRules.minLength},
      requireSpecialChar: ${cfg.passwordRules.requireSpecialChar},
      requireNumber: ${cfg.passwordRules.requireNumber},
    },
  },
  roles: [
${roles}
  ],
  registration: {
    standardFields: {
${standardFields}
    },
    customFields: ${customFields} as Array<{
      name: string; label: string; type: string;
      required: boolean; pii?: boolean; options?: string[];
    }>,
  },
  theme: {
    primaryColor: ${JSON.stringify(cfg.theme.primaryColor)},
    accentColor:  ${JSON.stringify(cfg.theme.accentColor)},
    font:         ${JSON.stringify(cfg.theme.font)},
    darkMode:     ${JSON.stringify(cfg.theme.darkMode)} as "toggle" | "light" | "dark",
    borderRadius: ${JSON.stringify(cfg.theme.borderRadius)},
  },
  security: {
    antiDebug: true,
    rateLimiting: {
      auth:  { windowMs: 900000, max: 10 },
      admin: { windowMs: 900000, max: 5  },
    },
    sessionTimeout: 1800,
    maxConcurrentSessions: 3,
    lockout: { attempts: 5, durationMs: 900000 },
  },
};

export type ProjectConfig = typeof projectConfig;
`;

        fs.writeFileSync(configPath, configContent, 'utf8');
        step('project.config.ts written ✓');

        // ── 4. Write .env.local ──────────────────────────────────────────────────
        step('Writing .env.local…');
        const envPath = path.join(ROOT, 'main-app', '.env.local');
        const envContent = [
            `MONGODB_URI=${cfg.mongoUri}`,
            `JWT_PRIVATE_KEY="${privateKey.replace(/\n/g, '\\n')}"`,
            `JWT_PUBLIC_KEY="${publicKey.replace(/\n/g, '\\n')}"`,
            `ADMIN_TOKEN=${adminToken}`,
            `NEXTAUTH_SECRET=${nextAuthSecret}`,
            `NEXTAUTH_URL=${cfg.baseUrl}`,
            `AES_ENCRYPTION_KEY=${aesKey}`,
            `REVALIDATE_SECRET=${revalidateSecret}`,
            `NODE_ENV=development`,
            `UPSTASH_REDIS_REST_URL=${cfg.upstashUrl || ''}`,
            `UPSTASH_REDIS_REST_TOKEN=${cfg.upstashToken || ''}`,
            '',
            '# OAuth (fill in if enabled)',
            `GOOGLE_CLIENT_ID=${cfg.oauthCredentials?.google?.clientId || ''}`,
            `GOOGLE_CLIENT_SECRET=${cfg.oauthCredentials?.google?.clientSecret || ''}`,
            `GITHUB_CLIENT_ID=${cfg.oauthCredentials?.github?.clientId || ''}`,
            `GITHUB_CLIENT_SECRET=${cfg.oauthCredentials?.github?.clientSecret || ''}`,
            `DISCORD_CLIENT_ID=${cfg.oauthCredentials?.discord?.clientId || ''}`,
            `DISCORD_CLIENT_SECRET=${cfg.oauthCredentials?.discord?.clientSecret || ''}`,
        ].join('\n');
        fs.writeFileSync(envPath, envContent, 'utf8');
        step('.env.local written ✓');

        // ── 4b. Write admin-app/.env ─────────────────────────────────────────────
        step('Writing admin-app/.env…');
        const adminEnvPath = path.join(ROOT, 'admin-app', '.env');
        const adminEnvContent = [
            `MAIN_APP_URL=${cfg.baseUrl}`,
            `REVALIDATE_SECRET=${revalidateSecret}`,
            `ADMIN_PORT=3002`
        ].join('\n');
        fs.writeFileSync(adminEnvPath, adminEnvContent, 'utf8');
        step('admin-app/.env written ✓');

        // ── 5. Connect to MongoDB and seed ───────────────────────────────────────
        step('Connecting to MongoDB…');
        const conn = await mongoose.createConnection(cfg.mongoUri.trim(), {
            serverSelectionTimeoutMS: 8000,
        }).asPromise();
        step('MongoDB connected ✓');

        const db = conn.db;

        // ── 5a. Seed system_config ────────────────────────────────────────────────
        step('Seeding system_config collection…');
        await db.collection('system_config').deleteMany({});
        await db.collection('system_config').insertOne({
            setup_complete: true,
            disabled_endpoints: [],
            maintenance_mode: false,
            maintenance_message: '',
            runtime_config: {},
            created_at: new Date(),
        });
        step('system_config seeded ✓');

        // ── 5b. Seed roles ─────────────────────────────────────────────────────────
        step('Seeding roles collection…');
        await db.collection('roles').deleteMany({});
        await db.collection('roles').insertMany(
            cfg.roles.map(r => ({
                name: r.name,
                color: r.color,
                isDefault: r.isDefault,
                permissions: {},
                created_at: new Date(),
            }))
        );
        step('Roles seeded ✓');

        // ── 5c. Seed admin user ────────────────────────────────────────────────────
        step('Creating admin user…');
        const passwordHash = await bcrypt.hash(cfg.adminAccount.password, 12);
        await db.collection('users').deleteMany({ email: cfg.adminAccount.email });
        await db.collection('users').insertOne({
            email: cfg.adminAccount.email,
            firstName: cfg.adminAccount.name.split(' ')[0] || cfg.adminAccount.name,
            lastName: cfg.adminAccount.name.split(' ').slice(1).join(' ') || '',
            passwordHash,
            role: 'admin',
            isActive: true,
            isDeleted: false,
            isVerified: true,
            totpEnabled: false,
            totpSecret: null,
            backupCodes: [],
            failedLoginAttempts: 0,
            lockoutUntil: null,
            lastLogin: null,
            sessions: [],
            created_at: new Date(),
            updated_at: new Date(),
        });
        step('Admin user created ✓');

        await conn.close();
        step('MongoDB connection closed ✓');

        // ── 6. Run generate-models.js ─────────────────────────────────────────────
        step('Generating user model scaffold…');
        try {
            const genScript = path.join(ROOT, 'scripts', 'generate-models.js');
            const registrationJson = JSON.stringify({ standardFields: cfg.standardFields, customFields: cfg.customFields || [] });
            execSync(`node "${genScript}" '${registrationJson}'`, { cwd: ROOT, timeout: 10000 });
            step('User model scaffold generated ✓');
        } catch (genErr) {
            step(`generate-models.js skipped (Phase 3): ${genErr.message}`, false);
        }

        // ── 7. Write logo if provided ─────────────────────────────────────────────
        if (cfg.logo) {
            step('Saving logo…');
            try {
                const matches = cfg.logo.match(/^data:image\/(png|jpg|jpeg|svg\+xml|gif|webp);base64,(.+)$/);
                if (matches) {
                    const ext = matches[1].replace('svg+xml', 'svg').replace('jpeg', 'jpg');
                    const data = Buffer.from(matches[2], 'base64');
                    const logoPath = path.join(ROOT, 'main-app', 'public', `logo.${ext}`);
                    fs.mkdirSync(path.dirname(logoPath), { recursive: true });
                    fs.writeFileSync(logoPath, data);
                    step(`Logo saved as public/logo.${ext} ✓`);
                }
            } catch (logoErr) {
                step(`Logo save failed (non-fatal): ${logoErr.message}`, false);
            }
        }

        // ── 8. Write .setup-done marker ───────────────────────────────────────────
        step('Writing .setup-done marker…');
        fs.writeFileSync(path.join(ROOT, '.setup-done'), new Date().toISOString(), 'utf8');
        step('.setup-done written ✓');

        step('🎉 Setup complete! Redirecting to your app…');
        done('http://localhost:3000/login');

    } catch (err) {
        console.error('[initialise] Fatal error:', err);
        fail(`Fatal error: ${err.message}`);
    }
};
