#!/usr/bin/env node
/**
 * scripts/generate-models.js
 * Reads the wizard's registration config (passed as JSON arg)
 * and regenerates the TypeScript type definitions for the dynamic
 * user fields in main-app/models/user.types.ts.
 *
 * Usage:
 *   node scripts/generate-models.js '{"standardFields":{...},"customFields":[...]}'
 *
 * Called automatically by setup-server/api/initialise.js after setup.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname.replace('/scripts', '');

function main() {
    let config;
    try {
        const raw = process.argv[2];
        if (!raw) {
            console.log('[generate-models] No config provided — skipping type generation.');
            return;
        }
        config = JSON.parse(raw);
    } catch (err) {
        console.error('[generate-models] Invalid JSON config:', err.message);
        process.exit(1);
    }

    const { standardFields = {}, customFields = [] } = config;

    const stdFieldLabels = {
        firstName: 'string',
        lastName: 'string',
        username: 'string',
        phone: 'string',
        dateOfBirth: 'string',
        avatar: 'string',
        company: 'string',
    };

    // Build interface lines for enabled standard fields
    const stdLines = Object.entries(standardFields)
        .filter(([, v]) => v.enabled)
        .map(([key, v]) => {
            const tsType = stdFieldLabels[key] || 'string';
            const optional = v.required ? '' : '?';
            return `  ${key}${optional}: ${tsType};`;
        });

    // Build interface lines for custom fields
    const customTypeMap = {
        text: 'string', number: 'number', date: 'Date',
        select: 'string', checkbox: 'boolean',
    };
    const customLines = customFields.map(f => {
        const tsType = customTypeMap[f.type] || 'string';
        const optional = f.required ? '' : '?';
        return `  ${f.name}${optional}: ${tsType};`;
    });

    const output = `/**
 * models/user.types.ts
 * AUTO-GENERATED by scripts/generate-models.js — DO NOT EDIT MANUALLY.
 * Re-generated each time the setup wizard runs.
 */

/** Dynamic fields added to the User model based on project configuration. */
export interface IUserDynamicFields {
${[...stdLines, ...customLines].join('\n') || '  // No dynamic fields configured'}
}
`;

    const outPath = path.join(ROOT, 'main-app', 'models', 'user.types.ts');
    fs.writeFileSync(outPath, output, 'utf8');
    console.log(`[generate-models] Written: ${outPath}`);
    console.log(`[generate-models] Standard fields: ${stdLines.length}, Custom fields: ${customLines.length}`);
}

main();
